// ⚠️ 本文件由 tools/balance-model/derive.ts 自动生成，请勿手改。
// 真源：tools/config-xlsx/balance.xlsx（Shares/Anchors/Caps/Overrides）→ npm run balance:derive。
// 消费端：各 tools/seed-*-xlsx.ts 的"框架接管列" + InventoryModel.SELL_FORGE_STONE 回填。
// 确定性产物（无时间戳）：balance:check 靠内容比对防漂移。
/* eslint-disable */
export const derivedValues = {
    "battle": {
        "statGrowthPerLevel": 0.0338,
        "expBase": 343,
        "enemyScales": [
            0.88,
            0.51,
            1.97,
            2.21,
            1.28,
            2.04,
            2.56,
            2.85,
            2.9,
            2.9
        ]
    },
    "equip": {
        "primaryScale": 1.298
    },
    "inlay": {
        "gemPrimaryScale": 1.114,
        "inscPrimaryScale": 5.199
    },
    "craft": {
        "tierCosts": {
            "tier_1": 58,
            "tier_2": 145,
            "tier_3": 290
        },
        "provisional": [
            "tier_2",
            "tier_3"
        ]
    },
    "sell": {
        "forgeStone": {
            "common": 5,
            "fine": 10,
            "rare": 20,
            "epic": 40,
            "legend": 80
        }
    },
    "report": {
        "solveK": {
            "kLevel": 0.6759,
            "kEquip": 1.2982,
            "kGem": 1.1137,
            "kInsc": 5.1986
        },
        "sharesActual": {
            "base": 0.05,
            "level": 0.2158,
            "equip": 0.4897,
            "gem": 0.1679,
            "inscription": 0.0767
        },
        "snapshotCounts": {
            "gems": 17.11,
            "gemAvgLevel": 1.61,
            "inscriptions": 5.13
        },
        "chestsPerRun": 1.756,
        "stonesPerRun": 9.63,
        "expPerRun": 261.2,
        "gemsExpected": 17.1,
        "scrollsExpected": 8.6,
        "iterations": 6,
        "progressPower": {
            "entry": [
                446,
                732,
                1089,
                1533,
                3107,
                3276,
                3621,
                5968,
                6370,
                6776
            ],
            "ready": [
                446,
                732,
                1089,
                2942,
                3107,
                3276,
                5415,
                5968,
                6370,
                10665
            ]
        },
        "pacingLoadouts": [
            {
                "name": "裸装",
                "hp": 0,
                "atk": 0
            },
            {
                "name": "过L4档",
                "hp": 1803,
                "atk": 180
            },
            {
                "name": "过L7档",
                "hp": 2892,
                "atk": 307
            },
            {
                "name": "毕业档",
                "hp": 4644,
                "atk": 508
            }
        ],
        "pacingPanels": {
            "entry": [
                [
                    {
                        "hp": 360,
                        "atk": 14,
                        "def": 10,
                        "range": 90,
                        "attackSpeed": 1,
                        "critRate": 0.05,
                        "critDmg": 0.5,
                        "dodgeRate": 0,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0,
                        "dmgReduce": 0.1,
                        "moveSpeed": 300,
                        "skillHaste": 0,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    },
                    {
                        "hp": 500,
                        "atk": 155,
                        "def": 2,
                        "range": 90,
                        "attackSpeed": 1.3,
                        "critRate": 0.25,
                        "critDmg": 1,
                        "dodgeRate": 0.05,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.1,
                        "dmgReduce": 0,
                        "moveSpeed": 300,
                        "skillHaste": 0,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    }
                ],
                [
                    {
                        "hp": 619,
                        "atk": 37,
                        "def": 13,
                        "range": 95.204,
                        "attackSpeed": 1.021,
                        "critRate": 0.057,
                        "critDmg": 0.501,
                        "dodgeRate": 0.004,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.002,
                        "dmgReduce": 0.105,
                        "moveSpeed": 300,
                        "skillHaste": 0,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    },
                    {
                        "hp": 759,
                        "atk": 179,
                        "def": 5,
                        "range": 95.204,
                        "attackSpeed": 1.321,
                        "critRate": 0.257,
                        "critDmg": 1.001,
                        "dodgeRate": 0.054,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.102,
                        "dmgReduce": 0.005,
                        "moveSpeed": 300,
                        "skillHaste": 0,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    }
                ],
                [
                    {
                        "hp": 929,
                        "atk": 65,
                        "def": 16,
                        "range": 100.83,
                        "attackSpeed": 1.043,
                        "critRate": 0.064,
                        "critDmg": 0.501,
                        "dodgeRate": 0.008,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.005,
                        "dmgReduce": 0.111,
                        "moveSpeed": 301,
                        "skillHaste": 0.001,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    },
                    {
                        "hp": 1074,
                        "atk": 211,
                        "def": 8,
                        "range": 100.83,
                        "attackSpeed": 1.343,
                        "critRate": 0.264,
                        "critDmg": 1.001,
                        "dodgeRate": 0.058,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.105,
                        "dmgReduce": 0.011,
                        "moveSpeed": 301,
                        "skillHaste": 0.001,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    }
                ],
                [
                    {
                        "hp": 1281,
                        "atk": 96,
                        "def": 20,
                        "range": 106.902,
                        "attackSpeed": 1.068,
                        "critRate": 0.072,
                        "critDmg": 0.502,
                        "dodgeRate": 0.013,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.007,
                        "dmgReduce": 0.117,
                        "moveSpeed": 301,
                        "skillHaste": 0.001,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.001,
                        "aoeDmgBonus": 0.001
                    },
                    {
                        "hp": 1431,
                        "atk": 247,
                        "def": 12,
                        "range": 106.902,
                        "attackSpeed": 1.368,
                        "critRate": 0.272,
                        "critDmg": 1.002,
                        "dodgeRate": 0.063,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.107,
                        "dmgReduce": 0.017,
                        "moveSpeed": 301,
                        "skillHaste": 0.001,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.001,
                        "aoeDmgBonus": 0.001
                    }
                ],
                [
                    {
                        "hp": 2230,
                        "atk": 190,
                        "def": 35,
                        "range": 119.634,
                        "attackSpeed": 1.119,
                        "critRate": 0.096,
                        "critDmg": 0.506,
                        "dodgeRate": 0.022,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.024,
                        "dmgReduce": 0.131,
                        "moveSpeed": 303,
                        "skillHaste": 0.003,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.002,
                        "aoeDmgBonus": 0.002
                    },
                    {
                        "hp": 2395,
                        "atk": 356,
                        "def": 26,
                        "range": 119.634,
                        "attackSpeed": 1.419,
                        "critRate": 0.296,
                        "critDmg": 1.006,
                        "dodgeRate": 0.072,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.124,
                        "dmgReduce": 0.031,
                        "moveSpeed": 303,
                        "skillHaste": 0.003,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.002,
                        "aoeDmgBonus": 0.002
                    }
                ],
                [
                    {
                        "hp": 2315,
                        "atk": 199,
                        "def": 37,
                        "range": 120.869,
                        "attackSpeed": 1.123,
                        "critRate": 0.098,
                        "critDmg": 0.507,
                        "dodgeRate": 0.023,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.027,
                        "dmgReduce": 0.133,
                        "moveSpeed": 304,
                        "skillHaste": 0.004,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.003,
                        "aoeDmgBonus": 0.003
                    },
                    {
                        "hp": 2480,
                        "atk": 366,
                        "def": 27,
                        "range": 120.869,
                        "attackSpeed": 1.423,
                        "critRate": 0.298,
                        "critDmg": 1.007,
                        "dodgeRate": 0.073,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.127,
                        "dmgReduce": 0.033,
                        "moveSpeed": 304,
                        "skillHaste": 0.004,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.003,
                        "aoeDmgBonus": 0.003
                    }
                ],
                [
                    {
                        "hp": 2479,
                        "atk": 216,
                        "def": 40,
                        "range": 122.433,
                        "attackSpeed": 1.129,
                        "critRate": 0.102,
                        "critDmg": 0.509,
                        "dodgeRate": 0.024,
                        "blockRate": 0.301,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.03,
                        "dmgReduce": 0.134,
                        "moveSpeed": 305,
                        "skillHaste": 0.006,
                        "basicDmgBonus": 0.002,
                        "skillDmgBonus": 0.002,
                        "singleDmgBonus": 0.003,
                        "aoeDmgBonus": 0.003
                    },
                    {
                        "hp": 2649,
                        "atk": 388,
                        "def": 30,
                        "range": 122.433,
                        "attackSpeed": 1.429,
                        "critRate": 0.302,
                        "critDmg": 1.009,
                        "dodgeRate": 0.074,
                        "blockRate": 0.001,
                        "blockRatio": 0,
                        "dmgBonus": 0.13,
                        "dmgReduce": 0.034,
                        "moveSpeed": 305,
                        "skillHaste": 0.006,
                        "basicDmgBonus": 0.002,
                        "skillDmgBonus": 0.002,
                        "singleDmgBonus": 0.003,
                        "aoeDmgBonus": 0.003
                    }
                ],
                [
                    {
                        "hp": 3453,
                        "atk": 325,
                        "def": 56,
                        "range": 135.527,
                        "attackSpeed": 1.178,
                        "critRate": 0.127,
                        "critDmg": 0.527,
                        "dodgeRate": 0.035,
                        "blockRate": 0.305,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.051,
                        "dmgReduce": 0.149,
                        "moveSpeed": 319,
                        "skillHaste": 0.027,
                        "basicDmgBonus": 0.017,
                        "skillDmgBonus": 0.017,
                        "singleDmgBonus": 0.004,
                        "aoeDmgBonus": 0.004
                    },
                    {
                        "hp": 3636,
                        "atk": 509,
                        "def": 45,
                        "range": 135.527,
                        "attackSpeed": 1.478,
                        "critRate": 0.327,
                        "critDmg": 1.027,
                        "dodgeRate": 0.085,
                        "blockRate": 0.005,
                        "blockRatio": 0,
                        "dmgBonus": 0.151,
                        "dmgReduce": 0.049,
                        "moveSpeed": 319,
                        "skillHaste": 0.027,
                        "basicDmgBonus": 0.017,
                        "skillDmgBonus": 0.017,
                        "singleDmgBonus": 0.004,
                        "aoeDmgBonus": 0.004
                    }
                ],
                [
                    {
                        "hp": 3592,
                        "atk": 340,
                        "def": 58,
                        "range": 137.743,
                        "attackSpeed": 1.186,
                        "critRate": 0.131,
                        "critDmg": 0.531,
                        "dodgeRate": 0.037,
                        "blockRate": 0.306,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.054,
                        "dmgReduce": 0.151,
                        "moveSpeed": 322,
                        "skillHaste": 0.03,
                        "basicDmgBonus": 0.019,
                        "skillDmgBonus": 0.019,
                        "singleDmgBonus": 0.005,
                        "aoeDmgBonus": 0.005
                    },
                    {
                        "hp": 3776,
                        "atk": 526,
                        "def": 48,
                        "range": 137.743,
                        "attackSpeed": 1.486,
                        "critRate": 0.331,
                        "critDmg": 1.031,
                        "dodgeRate": 0.087,
                        "blockRate": 0.006,
                        "blockRatio": 0,
                        "dmgBonus": 0.154,
                        "dmgReduce": 0.051,
                        "moveSpeed": 322,
                        "skillHaste": 0.03,
                        "basicDmgBonus": 0.019,
                        "skillDmgBonus": 0.019,
                        "singleDmgBonus": 0.005,
                        "aoeDmgBonus": 0.005
                    }
                ],
                [
                    {
                        "hp": 3736,
                        "atk": 357,
                        "def": 60,
                        "range": 140.055,
                        "attackSpeed": 1.195,
                        "critRate": 0.135,
                        "critDmg": 0.534,
                        "dodgeRate": 0.039,
                        "blockRate": 0.307,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.058,
                        "dmgReduce": 0.154,
                        "moveSpeed": 324,
                        "skillHaste": 0.034,
                        "basicDmgBonus": 0.022,
                        "skillDmgBonus": 0.022,
                        "singleDmgBonus": 0.005,
                        "aoeDmgBonus": 0.005
                    },
                    {
                        "hp": 3921,
                        "atk": 543,
                        "def": 50,
                        "range": 140.055,
                        "attackSpeed": 1.495,
                        "critRate": 0.335,
                        "critDmg": 1.034,
                        "dodgeRate": 0.089,
                        "blockRate": 0.007,
                        "blockRatio": 0,
                        "dmgBonus": 0.158,
                        "dmgReduce": 0.054,
                        "moveSpeed": 324,
                        "skillHaste": 0.034,
                        "basicDmgBonus": 0.022,
                        "skillDmgBonus": 0.022,
                        "singleDmgBonus": 0.005,
                        "aoeDmgBonus": 0.005
                    }
                ]
            ],
            "ready": [
                [
                    {
                        "hp": 360,
                        "atk": 14,
                        "def": 10,
                        "range": 90,
                        "attackSpeed": 1,
                        "critRate": 0.05,
                        "critDmg": 0.5,
                        "dodgeRate": 0,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0,
                        "dmgReduce": 0.1,
                        "moveSpeed": 300,
                        "skillHaste": 0,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    },
                    {
                        "hp": 500,
                        "atk": 155,
                        "def": 2,
                        "range": 90,
                        "attackSpeed": 1.3,
                        "critRate": 0.25,
                        "critDmg": 1,
                        "dodgeRate": 0.05,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.1,
                        "dmgReduce": 0,
                        "moveSpeed": 300,
                        "skillHaste": 0,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    }
                ],
                [
                    {
                        "hp": 619,
                        "atk": 37,
                        "def": 13,
                        "range": 95.204,
                        "attackSpeed": 1.021,
                        "critRate": 0.057,
                        "critDmg": 0.501,
                        "dodgeRate": 0.004,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.002,
                        "dmgReduce": 0.105,
                        "moveSpeed": 300,
                        "skillHaste": 0,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    },
                    {
                        "hp": 759,
                        "atk": 179,
                        "def": 5,
                        "range": 95.204,
                        "attackSpeed": 1.321,
                        "critRate": 0.257,
                        "critDmg": 1.001,
                        "dodgeRate": 0.054,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.102,
                        "dmgReduce": 0.005,
                        "moveSpeed": 300,
                        "skillHaste": 0,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    }
                ],
                [
                    {
                        "hp": 929,
                        "atk": 65,
                        "def": 16,
                        "range": 100.83,
                        "attackSpeed": 1.043,
                        "critRate": 0.064,
                        "critDmg": 0.501,
                        "dodgeRate": 0.008,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.005,
                        "dmgReduce": 0.111,
                        "moveSpeed": 301,
                        "skillHaste": 0.001,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    },
                    {
                        "hp": 1074,
                        "atk": 211,
                        "def": 8,
                        "range": 100.83,
                        "attackSpeed": 1.343,
                        "critRate": 0.264,
                        "critDmg": 1.001,
                        "dodgeRate": 0.058,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.105,
                        "dmgReduce": 0.011,
                        "moveSpeed": 301,
                        "skillHaste": 0.001,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0,
                        "aoeDmgBonus": 0
                    }
                ],
                [
                    {
                        "hp": 2150,
                        "atk": 181,
                        "def": 34,
                        "range": 118.508,
                        "attackSpeed": 1.114,
                        "critRate": 0.093,
                        "critDmg": 0.505,
                        "dodgeRate": 0.021,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.022,
                        "dmgReduce": 0.13,
                        "moveSpeed": 303,
                        "skillHaste": 0.003,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.002,
                        "aoeDmgBonus": 0.002
                    },
                    {
                        "hp": 2315,
                        "atk": 347,
                        "def": 24,
                        "range": 118.508,
                        "attackSpeed": 1.414,
                        "critRate": 0.293,
                        "critDmg": 1.005,
                        "dodgeRate": 0.071,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.122,
                        "dmgReduce": 0.03,
                        "moveSpeed": 303,
                        "skillHaste": 0.003,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.002,
                        "aoeDmgBonus": 0.002
                    }
                ],
                [
                    {
                        "hp": 2230,
                        "atk": 190,
                        "def": 35,
                        "range": 119.634,
                        "attackSpeed": 1.119,
                        "critRate": 0.096,
                        "critDmg": 0.506,
                        "dodgeRate": 0.022,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.024,
                        "dmgReduce": 0.131,
                        "moveSpeed": 303,
                        "skillHaste": 0.003,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.002,
                        "aoeDmgBonus": 0.002
                    },
                    {
                        "hp": 2395,
                        "atk": 356,
                        "def": 26,
                        "range": 119.634,
                        "attackSpeed": 1.419,
                        "critRate": 0.296,
                        "critDmg": 1.006,
                        "dodgeRate": 0.072,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.124,
                        "dmgReduce": 0.031,
                        "moveSpeed": 303,
                        "skillHaste": 0.003,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.002,
                        "aoeDmgBonus": 0.002
                    }
                ],
                [
                    {
                        "hp": 2315,
                        "atk": 199,
                        "def": 37,
                        "range": 120.869,
                        "attackSpeed": 1.123,
                        "critRate": 0.098,
                        "critDmg": 0.507,
                        "dodgeRate": 0.023,
                        "blockRate": 0.3,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.027,
                        "dmgReduce": 0.133,
                        "moveSpeed": 304,
                        "skillHaste": 0.004,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.003,
                        "aoeDmgBonus": 0.003
                    },
                    {
                        "hp": 2480,
                        "atk": 366,
                        "def": 27,
                        "range": 120.869,
                        "attackSpeed": 1.423,
                        "critRate": 0.298,
                        "critDmg": 1.007,
                        "dodgeRate": 0.073,
                        "blockRate": 0,
                        "blockRatio": 0,
                        "dmgBonus": 0.127,
                        "dmgReduce": 0.033,
                        "moveSpeed": 304,
                        "skillHaste": 0.004,
                        "basicDmgBonus": 0,
                        "skillDmgBonus": 0,
                        "singleDmgBonus": 0.003,
                        "aoeDmgBonus": 0.003
                    }
                ],
                [
                    {
                        "hp": 3233,
                        "atk": 301,
                        "def": 52,
                        "range": 133.404,
                        "attackSpeed": 1.17,
                        "critRate": 0.123,
                        "critDmg": 0.524,
                        "dodgeRate": 0.033,
                        "blockRate": 0.304,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.048,
                        "dmgReduce": 0.146,
                        "moveSpeed": 317,
                        "skillHaste": 0.023,
                        "basicDmgBonus": 0.014,
                        "skillDmgBonus": 0.014,
                        "singleDmgBonus": 0.004,
                        "aoeDmgBonus": 0.004
                    },
                    {
                        "hp": 3411,
                        "atk": 481,
                        "def": 42,
                        "range": 133.404,
                        "attackSpeed": 1.47,
                        "critRate": 0.323,
                        "critDmg": 1.024,
                        "dodgeRate": 0.083,
                        "blockRate": 0.004,
                        "blockRatio": 0,
                        "dmgBonus": 0.148,
                        "dmgReduce": 0.046,
                        "moveSpeed": 317,
                        "skillHaste": 0.023,
                        "basicDmgBonus": 0.014,
                        "skillDmgBonus": 0.014,
                        "singleDmgBonus": 0.004,
                        "aoeDmgBonus": 0.004
                    }
                ],
                [
                    {
                        "hp": 3453,
                        "atk": 325,
                        "def": 56,
                        "range": 135.527,
                        "attackSpeed": 1.178,
                        "critRate": 0.127,
                        "critDmg": 0.527,
                        "dodgeRate": 0.035,
                        "blockRate": 0.305,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.051,
                        "dmgReduce": 0.149,
                        "moveSpeed": 319,
                        "skillHaste": 0.027,
                        "basicDmgBonus": 0.017,
                        "skillDmgBonus": 0.017,
                        "singleDmgBonus": 0.004,
                        "aoeDmgBonus": 0.004
                    },
                    {
                        "hp": 3636,
                        "atk": 509,
                        "def": 45,
                        "range": 135.527,
                        "attackSpeed": 1.478,
                        "critRate": 0.327,
                        "critDmg": 1.027,
                        "dodgeRate": 0.085,
                        "blockRate": 0.005,
                        "blockRatio": 0,
                        "dmgBonus": 0.151,
                        "dmgReduce": 0.049,
                        "moveSpeed": 319,
                        "skillHaste": 0.027,
                        "basicDmgBonus": 0.017,
                        "skillDmgBonus": 0.017,
                        "singleDmgBonus": 0.004,
                        "aoeDmgBonus": 0.004
                    }
                ],
                [
                    {
                        "hp": 3592,
                        "atk": 340,
                        "def": 58,
                        "range": 137.743,
                        "attackSpeed": 1.186,
                        "critRate": 0.131,
                        "critDmg": 0.531,
                        "dodgeRate": 0.037,
                        "blockRate": 0.306,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.054,
                        "dmgReduce": 0.151,
                        "moveSpeed": 322,
                        "skillHaste": 0.03,
                        "basicDmgBonus": 0.019,
                        "skillDmgBonus": 0.019,
                        "singleDmgBonus": 0.005,
                        "aoeDmgBonus": 0.005
                    },
                    {
                        "hp": 3776,
                        "atk": 526,
                        "def": 48,
                        "range": 137.743,
                        "attackSpeed": 1.486,
                        "critRate": 0.331,
                        "critDmg": 1.031,
                        "dodgeRate": 0.087,
                        "blockRate": 0.006,
                        "blockRatio": 0,
                        "dmgBonus": 0.154,
                        "dmgReduce": 0.051,
                        "moveSpeed": 322,
                        "skillHaste": 0.03,
                        "basicDmgBonus": 0.019,
                        "skillDmgBonus": 0.019,
                        "singleDmgBonus": 0.005,
                        "aoeDmgBonus": 0.005
                    }
                ],
                [
                    {
                        "hp": 4975,
                        "atk": 493,
                        "def": 79,
                        "range": 156.199,
                        "attackSpeed": 1.254,
                        "critRate": 0.162,
                        "critDmg": 0.559,
                        "dodgeRate": 0.052,
                        "blockRate": 0.313,
                        "blockRatio": 0.5,
                        "dmgBonus": 0.079,
                        "dmgReduce": 0.171,
                        "moveSpeed": 344,
                        "skillHaste": 0.063,
                        "basicDmgBonus": 0.044,
                        "skillDmgBonus": 0.044,
                        "singleDmgBonus": 0.006,
                        "aoeDmgBonus": 0.006
                    },
                    {
                        "hp": 5173,
                        "atk": 692,
                        "def": 68,
                        "range": 156.199,
                        "attackSpeed": 1.554,
                        "critRate": 0.362,
                        "critDmg": 1.059,
                        "dodgeRate": 0.102,
                        "blockRate": 0.013,
                        "blockRatio": 0,
                        "dmgBonus": 0.179,
                        "dmgReduce": 0.071,
                        "moveSpeed": 344,
                        "skillHaste": 0.063,
                        "basicDmgBonus": 0.044,
                        "skillDmgBonus": 0.044,
                        "singleDmgBonus": 0.006,
                        "aoeDmgBonus": 0.006
                    }
                ]
            ]
        }
    }
} as const;
